### ISSUE TITLE
Configure skipPattern in web.xml

### ISSUE THREAD

**Issue by wyfrel** [opentracing-contrib/java-jaxrs#96] opened 2018-09-07 19:00 UTC
Hi,

I would like to configure skipPattern in web.xml. Is there a way to do this?

Thank you !

**Comment by pavolloffay** [comment] 2018-09-18 09:40
@wyfrel hi, could you please describe your use case?  Why do you need to define it in web.xml? 

The fiter itself cannot be configured in web.xml as it requires multiple objects to be provided.

**Comment by wyfrel** [comment] 2018-09-18 10:44
@pavolloffay  : thx for your answer. 

I fact the need is to be able to configure the skippattern when starting the `ServerTracingDynamicFeature` with the default constructor. The version of restEasy that i (must) use doesn't boostrap correctly `ServerTracingDynamicFeature` when it's defined via the `getSingletons()` method of `javax.ws.rs.core.Application`. In debbuging i can see that the configure method of `ServerTracingDynamicFeature` is never called.

**Comment by pavolloffay** [comment] 2018-09-18 10:52
> I fact the need is to be able to configure the skippattern when starting the ServerTracingDynamicFeature with the default constructor.

Do you mean when the feature is auto-discovered by runtime? I am planning to remove `@Provider` from the feature so users can provide a configured provider e.g. with skip pattern.

> ServerTracingDynamicFeature when it's defined via the getSingletons() method of javax.ws.rs.core.Application

Maybe because the runtime auto discovered it and the provider added to singletons is skipped.
If the configure was never called you would not get any traces because it registers filters which create spans.

**Comment by wyfrel** [comment] 2018-09-18 11:15
> Do you mean when the feature is auto-discovered by runtime?

I configure it via the `getClasses()` method of `javax.ws.rs.core.Application`

>Maybe because the runtime auto discovered it and the provider added to singletons is skipped.

I've just try to removed the `@provider` from ServerTracingDynamicFeature  and try to define ServerTracingDynamicFeature  via getSingleton but `configure(ResourceInfo resourceInfo, FeatureContext context)` method is never called.

**Comment by pavolloffay** [comment] 2018-09-18 11:38
And do you get any traces? 

@wyfrel do you have a reproducer? It seems more like a configuration issue.

**Comment by wyfrel** [comment] 2018-09-22 19:12
@pavolloffay  : Sorry for the delay. I add no time to produce a working example (without company code ;-)) before today.

I publish it here : https://github.com/wyfrel/helloworld-opencontrib-jaxrs

In 'be.wyfrel.helloworld.application.HelloWorldApplication' i add in comment the configurations that aren't working

**Comment by wyfrel** [comment] 2018-09-28 20:42
@pavolloffay : did you had Time to check my reproducer ?

**Comment by pavolloffay** [comment] 2018-10-08 12:51
I had a look at the reproducer. I have a couple of comments: 

* you forgot to register `SpanFinishingFilter`
* The custom tracing feature can be configured by creating dynamic feature which wrap the one in this repository. Then the feature has to be added to `resteasy.providers`. Not sure why automatic discovery does not work maybe because how the whole deployment is configured. In standard WF deployment it works well.

The working example is here https://github.com/wyfrel/helloworld-opencontrib-jaxrs/pull/1/files

Interesting is that adding a dynamicfeature to singleton map does not work (in WF). Therefore I think the way to go is to create a wrapper for `ServerTracingDynamicFeature` like in the linked PR.

**Comment by pavolloffay** [comment] 2018-10-08 15:18
@wyfrel  I got working configuration via `getSingletos`. There is probably something wrong with the configuration. If you comment 

```
  <!--<listener>-->
    <!--<listener-class>org.jboss.resteasy.plugins.server.servlet.ResteasyBootstrap</listener-class>-->
  <!--</listener>-->
  <!--<listener>-->
    <!--<listener-class>org.jboss.resteasy.plugins.spring.SpringContextLoaderListener</listener-class>-->
  <!--</listener>--> 
```

Then all resources specified in singletons are loaded.

**Comment by wyfrel** [comment] 2018-10-08 18:37
@pavolloffay  : Thx for all these information!! I'll take a look at them !!

**Comment by pavolloffay** [comment] 2018-10-10 15:10
@wyfrel I will close this one in favor of #102. 

Let us know if you solved the original issue.

**Closed by pavolloffay** 2018-10-10 15:10 UTC
